# Server
server:
  port: 8080
  server:
    tomcat:
      uri-encoding: utf-8
# logging
logging:
  level:
    root: info
#  file: log/run.log
# Spring
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      url: jdbc:mysql://localhost:3306/mall?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.linya.admin.po


